week_4/timetracking/config/routes.rb
Rails.application.routes.draw do
	get '/', to: 'site#home'
	get '/contact', to: 'site#contact'
	
	resources :projects, only: [:index, :show, :new, :create] do
	resources :time_entries, except: [:show]
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

week_4/timetracking/app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries
	validates :name, presence: true, uniqueness: true, length: { maximum: 30 }, format: { with: /\w/}

#========================================================================
#========================= Methods ======================================
#========================================================================

	def self.clean_old
		old_projects = Project.where('updated_at < ?', (Time.now - 1.week))
		old_projects.destroy_all
	end

#========================================================================
#====================== Relationships ===================================
#========================================================================
	

#========================================================================
#====================== Validations =====================================
#========================================================================


end

week_4/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	
#========================================================================
#====================== Relationships ===================================
#========================================================================	
	belongs_to :project


#========================================================================
#====================== Validations =====================================
#========================================================================

	validates :hours, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
	validates :minutes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
	validates :date, presence: true
	validates_associated :project

end

week_4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
#================================================================================
#================================================================================
	def index
		@projects_array = Project.order(created_at: "desc").limit(10)

		render 'index'	
	end
#================================================================================
#================================================================================
	def new
		@my_project=Project.new
		render "new"
	end
#================================================================================
#================================================================================
	def create
		@my_project = Project.new(
			:name => params[:project][:name],
			:description => params[:project][:description])
		@my_project.save
		redirect_to "/projects/#{@my_project.id}"
	end
#================================================================================
#================================================================================
	def show
		@my_project = Project.find(params[:id])

		render "show"
	end
#================================================================================
#================================================================================
end

week_4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
		render 'home'
	end

	def contact
		render 'contact'
	end
end

week_4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

#============================================================================================
#============================================================================================

	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries
		render "index"
	end

#============================================================================================
#============================================================================================

	def new
		@my_project = Project.find(params[:project_id])
		@new_entry = @my_project.time_entries.new
		render "new"
	end

#============================================================================================
#============================================================================================

	def create
		@my_project = Project.find(params[:project_id])
		@new_entry = @my_project.time_entries.new(entry_params)
		if @new_entry.save
		flash[:notice] = "Project created successfully"
		redirect_to project_time_entries_path
		else
		flash[:alert] = "Something went wrong. Please try again."
		redirect_to new_project_time_entry_path
	end
	end

#============================================================================================
#============================================================================================

	def edit
		@my_project = Project.find params[:project_id]
		@new_entry = @my_project.time_entries.find params[:id]
		render "edit"
	end

#============================================================================================
#============================================================================================

	def update
			@my_project = Project.find_by(id: params[:project_id])
			@new_entry = @my_project.time_entries.find_by(id: params[:id])
			if @new_entry.update(entry_params)
			flash[:notice] = "Project updated successfully"
			redirect_to project_time_entries_path
			else
			flash[:alert] = "Something went wrong. Please try again."	
			render "edit"
			end
	end

#============================================================================================
#============================================================================================

	def destroy
		@my_project = Project.find params[:project_id]
		@new_entry = @my_project.time_entries.find params[:id]
		
		@new_entry.destroy 

		redirect_to(project_time_entries_path(@my_project))
	end

#============================================================================================
#========================== *** PRIVATE *** =================================================
#============================================================================================

	private

	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date, :comments)
	end	

#============================================================================================
#============================================================================================

end

week_4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week_4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week_4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
  	<% if flash[:notice] %> 
  		<%= flash[:notice] %> 
	<% else %>
		<%= flash[:alert] %>  
	<% end %>

    <%= yield %>
  
  </body>
</html>

week_4/timetracking/app/views/time_entries/_form.html.erb
<% if @new_entry.errors.any? %>
	<ul>

		<% @new_entry.errors.full_messages.each do |error_msg| %>
		<li> <%= error_msg %> </li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@my_project, @new_entry] do |f| %>
		<%= f.label :hours %>
		<%= f.text_field :hours %>
	<br>
		<%= f.label :minutes %>
		<%= f.text_field :minutes %>
	<br>
		<%= f.label :date %>
		<%= f.date_field :date %>
	<br>
		<%= f.label :comments %>
		<%= f.text_area :comments %>
	<br>	
		<%= f.button %>
<% end %>

week_4/timetracking/app/views/time_entries/edit.html.erb
<%= render "form" %>

week_4/timetracking/app/views/time_entries/index.html.erb
<h1> <%= @my_project.name %> </h1>
<ul>
	<% @my_entries.each do |entry| %>
	<li>
		<%= entry.hours %> h
		<%= entry.minutes %> m
		<%= entry.date %> 
	
		<a href='/projects/<%= @my_project.id %>/time_entries/<%= entry.id %>/edit'>
		Edit
		</a>
		<a href='<%= project_time_entry_path(@my_project, entry) %>', data-confirm="are you sure?", data-method="delete">
		Delete
		</a>	
	</li>
	<% end %>
</ul>

<a href="/projects/<%= @my_project.id %>/time_entries/new">
	Add a Time Entry to <%= @my_project.name %>
</a>
<br>

week_4/timetracking/app/views/time_entries/new.html.erb
<h1> Add a Time Entry </h1>

<%= render "form" %>